# Building word count vectors with scikit-learn


## CountVectorizer for text classification
It's time to begin building your text classifier! The data has been loaded into a DataFrame called df. Explore it in the IPython Shell to investigate what columns you can use. The .head() method is particularly informative.

In this exercise, you'll use pandas alongside scikit-learn to create a sparse text vectorizer you can use to train and test a simple supervised model. To begin, you'll set up a CountVectorizer and investigate some of its features.

### code : 1 dataframe

In [5]:
from uploadfromdatacamp import saveFromFileIO

#uploadToFileIO(df)
tobedownloaded="{pandas.core.frame.DataFrame: {'df.csv': 'https://file.io/wmCKCD'}}"
prefix='data_from_datacamp/Chap4-Exercise1.1_'
#saveFromFileIO(tobedownloaded, prefix=prefix, proxy="10.225.92.1:80")


In [6]:
import pandas as pd

df=pd.read_csv(prefix+'df.csv',index_col=0, sep="|")


In [7]:
df

Unnamed: 0.1                                              title  \
0             8476                       You Can Smell Hillary’s Fear   
1            10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2             3608        Kerry to go to Paris in gesture of sympathy   
3            10142  Bernie supporters on Twitter erupt in anger ag...   
4              875   The Battle of New York: Why This Primary Matters   
...            ...                                                ...   
6330          4490  State Department says it can't find emails fro...   
6331          8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332          8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333          4021  In Ethiopia, Obama seeks progress on peace, se...   
6334          4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

### code

In [9]:
# Import the necessary modules
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

# Print the head of df
print(df.head())

# Create a series to store the labels: y
y = df["label"]

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(df["text"], y, test_size=0.33, random_state=53)

# Initialize a CountVectorizer object: count_vectorizer
count_vectorizer = CountVectorizer(stop_words='english')

# Transform the training data using only the 'text' column values: count_train 
count_train = count_vectorizer.fit_transform(X_train)

# Transform the test data using only the 'text' column values: count_test 
count_test = count_vectorizer.transform(X_test)

# Print the first 10 features of the count_vectorizer
print(count_vectorizer.get_feature_names()[:10])

   Unnamed: 0.1                                              title  \
0          8476                       You Can Smell Hillary’s Fear   
1         10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2          3608        Kerry to go to Paris in gesture of sympathy   
3         10142  Bernie supporters on Twitter erupt in anger ag...   
4           875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL  
['00', '000', '0000', '00000031', '000035', '00006', '0001', '0001pt', '000ft', '000km']


## TfidfVectorizer for text classification
Similar to the sparse CountVectorizer created in the previous exercise, you'll work on creating tf-idf vectors for your documents. You'll set up a TfidfVectorizer and investigate some of its features.

In this exercise, you'll use pandas and sklearn along with the same X_train, y_train and X_test, y_test DataFrames and Series you created in the last exercise.

### code

In [10]:
# Import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize a TfidfVectorizer object: tfidf_vectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

# Transform the training data: tfidf_train 
tfidf_train = tfidf_vectorizer.fit_transform(X_train)

# Transform the test data: tfidf_test 
tfidf_test = tfidf_vectorizer.transform(X_test)

# Print the first 10 features
print(tfidf_vectorizer.get_feature_names()[:10])

# Print the first 5 vectors of the tfidf training data
print(tfidf_train.A[:5])


['00', '000', '0000', '00000031', '000035', '00006', '0001', '0001pt', '000ft', '000km']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Inspecting the vectors
To get a better idea of how the vectors work, you'll investigate them by converting them into pandas DataFrames.

Here, you'll use the same data structures you created in the previous two exercises (count_train, count_vectorizer, tfidf_train, tfidf_vectorizer) as well as pandas, which is imported as pd.

### code

In [11]:
# Create the CountVectorizer DataFrame: count_df
count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())

# Create the TfidfVectorizer DataFrame: tfidf_df
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())

# Print the head of count_df
print(count_df.head())

# Print the head of tfidf_df
print(tfidf_df.head())

# Calculate the difference in columns: difference
difference = set(tfidf_df.columns) - set(count_df.columns)
print(difference)

# Check whether the DataFrames are equal
print(count_df.equals(tfidf_df))


   00  000  0000  00000031  000035  00006  0001  0001pt  000ft  000km  ...  \
0   0    0     0         0       0      0     0       0      0      0  ...   
1   0    0     0         0       0      0     0       0      0      0  ...   
2   0    0     0         0       0      0     0       0      0      0  ...   
3   0    0     0         0       0      0     0       0      0      0  ...   
4   0    0     0         0       0      0     0       0      0      0  ...   

   حلب  عربي  عن  لم  ما  محاولات  من  هذا  والمرضى  ยงade  
0    0     0   0   0   0        0   0    0        0      0  
1    0     0   0   0   0        0   0    0        0      0  
2    0     0   0   0   0        0   0    0        0      0  
3    0     0   0   0   0        0   0    0        0      0  
4    0     0   0   0   0        0   0    0        0      0  

[5 rows x 56922 columns]
    00  000  0000  00000031  000035  00006  0001  0001pt  000ft  000km  ...  \
0  0.0  0.0   0.0       0.0     0.0    0.0   0.0     0.0    

# Training and testing a classification model with scikit-learn


## Training and testing the "fake news" model with CountVectorizer
Now it's your turn to train the "fake news" model using the features you identified and extracted. In this first exercise you'll train and test a Naive Bayes model using the CountVectorizer data.

The training and test sets have been created, and count_vectorizer, count_train, and count_test have been computed.

### init

In [12]:
from uploadfromdatacamp import saveFromFileIO
#import scipy
#scipy.sparse.save_npz('count_test.npz', count_test)
#scipy.sparse.save_npz('count_train.npz', count_train)
#print(uploadToFileIO_pushto_fileio('count_test.npz'))
#print(uploadToFileIO_pushto_fileio('count_train.npz'))

#uploadToFileIO(y_train, y_test)

tobedownloaded="""{pandas.core.series.Series: {'y_test.csv': 'https://file.io/Ox7O8S',
  'y_train.csv': 'https://file.io/BByC19'},
                csr_matrix:{
                    'count_test.npz': 'https://file.io/AxwzIb',
                    'count_train.npz': 'https://file.io/LkaENZ'
                }}"""
prefix='data_from_datacamp/Chap4-Exercise2.1_'
#saveFromFileIO(tobedownloaded, prefix=prefix, proxy="10.225.92.1:80")


{pandas.core.series.Series: {"y_test.csv": "https://file.io/Ox7O8S",
  "y_train.csv": "https://file.io/BByC19"},
                csr_matrix:{
                    "count_test.npz": "https://file.io/AxwzIb",
                    "count_train.npz": "https://file.io/LkaENZ"
                }}
{'pandas.core.series.Series': {'y_test.csv': 'https://file.io/Ox7O8S', 'y_train.csv': 'https://file.io/BByC19'}, 'csr_matrix': {'count_test.npz': 'https://file.io/AxwzIb', 'count_train.npz': 'https://file.io/LkaENZ'}}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20544    0 20544    0     0  23005      0 --:--:-- --:--:-- --:--:-- 23005
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                 

In [14]:
import scipy

count_test = scipy.sparse.load_npz(prefix+'count_test.npz')
count_train = scipy.sparse.load_npz(prefix+'count_train.npz')

y_test  =pd.read_csv(prefix+'y_test.csv', index_col=0, header=None,squeeze=True)
y_train =pd.read_csv(prefix+'y_train.csv', index_col=0, header=None,squeeze=True)

In [15]:
count_vectorizer = CountVectorizer(stop_words='english')


### code

In [17]:
# Import the necessary modules
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

# Instantiate a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

# Fit the classifier to the training data
nb_classifier.fit(count_train, y_train)

# Create the predicted tags: pred
pred = nb_classifier.predict(count_test)

# Calculate the accuracy score: score
score = metrics.accuracy_score(y_test, pred)
print(score)

# Calculate the confusion matrix: cm
cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
print(cm)


0.893352462936394
[[ 865  143]
 [  80 1003]]


## Training and testing the "fake news" model with TfidfVectorizer
Now that you have evaluated the model using the CountVectorizer, you'll do the same using the TfidfVectorizer with a Naive Bayes model.

The training and test sets have been created, and tfidf_vectorizer, tfidf_train, and tfidf_test have been computed. Additionally, MultinomialNB and metrics have been imported from, respectively, sklearn.naive_bayes and sklearn.

### init

In [18]:
from uploadfromdatacamp import saveFromFileIO

fromDatacamp = """
import scipy
scipy.sparse.save_npz('tfidf_test.npz', tfidf_test)
scipy.sparse.save_npz('tfidf_train.npz', tfidf_train)
uploadToFileIO_pushto_fileio('tfidf_test.npz')
uploadToFileIO_pushto_fileio('tfidf_train.npz')
uploadToFileIO(y_train, y_test)
"""

tobedownloaded="""{pandas.core.series.Series: {'y_test.csv': 'https://file.io/mzBimd',
  'y_train.csv': 'https://file.io/1Ox2bh'},
                csr_matrix:{
                    'tfidf_test.npz': 'https://file.io/2xhPOZ',
                    'tfidf_train.npz': 'https://file.io/WAM179'
                }}"""
prefix='data_from_datacamp/Chap4-Exercise2.2_'
#saveFromFileIO(tobedownloaded, prefix=prefix, proxy="10.225.92.1:80")


{pandas.core.series.Series: {"y_test.csv": "https://file.io/mzBimd",
  "y_train.csv": "https://file.io/1Ox2bh"},
                csr_matrix:{
                    "count_test.npz": "https://file.io/2xhPOZ",
                    "count_train.npz": "https://file.io/WAM179"
                }}
{'pandas.core.series.Series': {'y_test.csv': 'https://file.io/mzBimd', 'y_train.csv': 'https://file.io/1Ox2bh'}, 'csr_matrix': {'count_test.npz': 'https://file.io/2xhPOZ', 'count_train.npz': 'https://file.io/WAM179'}}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 20544    0 20544    0     0  17664      0 --:--:--  0:00:01 --:--:-- 17679
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                 

In [19]:
import scipy

tfidf_test = scipy.sparse.load_npz(prefix+'tfidf_test.npz')
tfidf_train = scipy.sparse.load_npz(prefix+'tfidf_train.npz')

y_test  =pd.read_csv(prefix+'y_test.csv', index_col=0, header=None,squeeze=True)
y_train =pd.read_csv(prefix+'y_train.csv', index_col=0, header=None,squeeze=True)

In [20]:
# Import the necessary modules
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

### code

In [21]:
# Create a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

# Fit the classifier to the training data
nb_classifier.fit(tfidf_train, y_train)

# Create the predicted tags: pred
pred = nb_classifier.predict(tfidf_test)

# Calculate the accuracy score: score
score = metrics.accuracy_score(y_test, pred)
print(score)

# Calculate the confusion matrix: cm
cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])
print(cm)

0.8565279770444764
[[ 739  269]
 [  31 1052]]


# Simple NLP, complex problems


## Improving your model
Your job in this exercise is to test a few different alpha levels using the Tfidf vectors to determine if there is a better performing combination.

The training and test sets have been created, and tfidf_vectorizer, tfidf_train, and tfidf_test have been computed.

### code

In [24]:
# Create the list of alphas: alphas
alphas = np.arange(0,1,0.1)

# Define train_and_predict()
def train_and_predict(alpha):
    # Instantiate the classifier: nb_classifier
    nb_classifier = MultinomialNB(alpha=alpha)
    # Fit to the training data
    nb_classifier.fit(tfidf_train, y_train)
    # Predict the labels: pred
    pred = nb_classifier.predict(tfidf_test)
    # Compute accuracy: score
    score = metrics.accuracy_score(y_test, pred)
    return score

# Iterate over the alphas and print the corresponding score
for alpha in alphas:
    print('Alpha: ', alpha)
    print('Score: ', train_and_predict(alpha))
    print()


Alpha:  0.0
Score:  0.8813964610234337

Alpha:  0.1
Score:  0.8976566236250598

Alpha:  0.2
Score:  0.8938307030129125

Alpha:  0.30000000000000004
Score:  0.8900047824007652

Alpha:  0.4
Score:  0.8857006217120995

Alpha:  0.5
Score:  0.8842659014825442

Alpha:  0.6000000000000001
Score: 

C:\Users\F279814\AppData\Local\Continuum\anaconda3\envs\datacamp\lib\site-packages\sklearn\naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


 0.874701099952176

Alpha:  0.7000000000000001
Score:  0.8703969392635102

Alpha:  0.8
Score:  0.8660927785748446

Alpha:  0.9
Score:  0.8589191774270684



## Inspecting your model
Now that you have built a "fake news" classifier, you'll investigate what it has learned. You can map the important vector weights back to actual words using some simple inspection techniques.

You have your well performing tfidf Naive Bayes classifier available as nb_classifier, and the vectors as tfidf_vectorizer.

### code

In [25]:
# Get the class labels: class_labels
class_labels = nb_classifier.classes_

# Extract the features: feature_names
feature_names = tfidf_vectorizer.get_feature_names()

# Zip the feature names together with the coefficient array and sort by weights: feat_with_weights
feat_with_weights = sorted(zip(nb_classifier.coef_[0], feature_names))

# Print the first class label and the top 20 feat_with_weights entries
print(class_labels[0], feat_with_weights[:20])

# Print the second class label and the bottom 20 feat_with_weights entries
print(class_labels[1], feat_with_weights[-20:])


FAKE [(-11.316312804238807, '0000'), (-11.316312804238807, '000035'), (-11.316312804238807, '0001'), (-11.316312804238807, '0001pt'), (-11.316312804238807, '000km'), (-11.316312804238807, '0011'), (-11.316312804238807, '006s'), (-11.316312804238807, '007'), (-11.316312804238807, '007s'), (-11.316312804238807, '008s'), (-11.316312804238807, '0099'), (-11.316312804238807, '00am'), (-11.316312804238807, '00p'), (-11.316312804238807, '00pm'), (-11.316312804238807, '014'), (-11.316312804238807, '015'), (-11.316312804238807, '018'), (-11.316312804238807, '01am'), (-11.316312804238807, '020'), (-11.316312804238807, '023')]
REAL [(-7.742481952533027, 'states'), (-7.717550034444668, 'rubio'), (-7.703583809227384, 'voters'), (-7.654774992495461, 'house'), (-7.649398936153309, 'republicans'), (-7.6246184189367, 'bush'), (-7.616556675728882, 'percent'), (-7.545789237823644, 'people'), (-7.516447881078008, 'new'), (-7.448027933291952, 'party'), (-7.4111484102034755, 'cruz'), (-7.410910239085596, 's